# Generated by Django 5.2.4 on 2025-08-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('staff', 'staff'), ('user', 'user')], default='user', max_length=50),
        ),
    ]
