# Generated by Django 5.2.4 on 2025-08-10 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_card', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recharg_history',
            old_name='recharg_history',
            new_name='recharg_history_id',
        ),
    ]
