# Generated by Django 5.2.4 on 2025-08-10 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_card', '0003_rename_recharg_history_recharg_history_recharg_history_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardState',
            fields=[
                ('Card_State_id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('plan', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rout_no', models.CharField(max_length=100)),
                ('rout', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TravelMode',
            fields=[
                ('travel_mode_id', models.AutoField(primary_key=True, serialize=False)),
                ('mode', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TravelPlanState',
            fields=[
                ('travel_plan_state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('card_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart_card.cardstate')),
            ],
        ),
        migrations.RenameModel(
            old_name='Payment_Type',
            new_name='PaymentType',
        ),
        migrations.CreateModel(
            name='RechargHistory',
            fields=[
                ('recharg_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('recharged_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recharged_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart_card.card')),
                ('payment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart_card.paymenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('destination_id', models.AutoField(primary_key=True, serialize=False)),
                ('fee_stage', models.IntegerField()),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destination', models.CharField(max_length=100)),
                ('rout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart_card.rout')),
            ],
        ),
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('travel_plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart_card.card')),
                ('from_destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_from', to='smart_card.destination')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart_card.plan')),
                ('to_destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_to', to='smart_card.destination')),
                ('travel_mode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart_card.travelmode')),
                ('travel_plan_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart_card.travelplanstate')),
            ],
        ),
        migrations.CreateModel(
            name='InterchangingPoint',
            fields=[
                ('interchanging_point_id', models.AutoField(primary_key=True, serialize=False)),
                ('ineterchangin_point', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart_card.destination')),
                ('travel_plane', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart_card.travelplan')),
            ],
        ),
        migrations.DeleteModel(
            name='Recharg_History',
        ),
    ]
