# Generated by Django 5.2.3 on 2025-08-13 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_card', '0006_rename_ineterchangin_point_interchangingpoint_ineterchanging_point_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardCategory',
            fields=[
                ('card_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_category', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='travelplan',
            name='travel_mode',
        ),
        migrations.AddField(
            model_name='card',
            name='card_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart_card.cardcategory'),
        ),
        migrations.DeleteModel(
            name='TravelMode',
        ),
    ]
