# Generated by Django 5.2.3 on 2025-08-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_card', '0007_cardcategory_remove_travelplan_travel_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardcategory',
            name='card_category_id',
        ),
        migrations.AddField(
            model_name='cardcategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cardcategory',
            name='card_category',
            field=models.CharField(choices=[('BUS', 'Bus'), ('TRAIN', 'Train')], default='BUS', max_length=10),
        ),
    ]
