# Generated by Django 5.2.3 on 2025-08-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_card', '0008_remove_cardcategory_card_category_id_cardcategory_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardstate',
            name='Card_State_id',
        ),
        migrations.AddField(
            model_name='cardstate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cardstate',
            name='state',
            field=models.CharField(choices=[('ACTIVATE', 'Activate'), ('DISABLED', 'Desabled')], default='ACTIVATED', max_length=20),
        ),
    ]
