# Generated by Django 5.2.3 on 2025-08-18 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_card', '0009_remove_cardstate_card_state_id_cardstate_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart_card.cardstate'),
        ),
    ]
