# Generated by Django 5.2.4 on 2025-08-06 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_card', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Type',
            fields=[
                ('payment_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(default=56565, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='contact_no',
            field=models.CharField(default=123546987, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Recharg_History',
            fields=[
                ('recharg_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('recharged_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recharged_at', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart_card.payment_type')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
