# Generated by Django 5.2.4 on 2025-08-10 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_card', '0004_cardstate_plan_rout_travelmode_travelplanstate_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_state',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart_card.cardstate'),
        ),
        migrations.AlterField(
            model_name='interchangingpoint',
            name='ineterchangin_point',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart_card.destination'),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='from_destination',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_from', to='smart_card.destination'),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='plan',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart_card.plan'),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='to_destination',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_to', to='smart_card.destination'),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='travel_mode',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart_card.travelmode'),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='travel_plan_state',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart_card.travelplanstate'),
        ),
    ]
