# Generated by Django 5.2.4 on 2025-08-10 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_card', '0005_alter_card_card_state_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interchangingpoint',
            old_name='ineterchangin_point',
            new_name='ineterchanging_point',
        ),
        migrations.RenameField(
            model_name='interchangingpoint',
            old_name='travel_plane',
            new_name='travel_plan',
        ),
    ]
